/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Alec.Tunbridge' at '24/04/15 09:39' with Gradle 1.10
 *
 * @author Alec.Tunbridge, @date 24/04/15 09:39
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
